# Generated by Django 3.0.1 on 2020-01-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='timestamp',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
